#!/usr/bin/env bash

# Ensure CLI is installed
# shellcheck disable=SC2164
cd ./dev-cli
if ! yarn check --integrity 2>/dev/null | grep -q 'success Folder in sync.'; then
    echo "Installing the cli...";
    yarn install;
    echo "";
fi
cd ../;

if [[ "${1}" = "build" ]]; then
    # shellcheck disable=SC2164
    cd ./dev-cli;
    yarn build;
    exit;
fi

if [[ "${1}" = "dev-mode" ]]; then
    # Send all arguments exect the firstone
    ./dev-cli/bin/dev "${@:2}";
    exit;
fi

./dev-cli/bin/run "${@}";
