version: '3.7'

services:
  utility:
    env_file:
      - .env
      - .env.local
    image: ubuntu:18.04
    restart: always
    container_name: buzzingpixel-utility
    volumes:
      - .:/opt/project
      - log-volume:/log-volume
      - storage-volume:/storage-volume
    command: bash -c "chmod +x /opt/project/docker/utility/prod.sh && /opt/project/docker/utility/prod.sh"

  app:
    restart: always
    volumes:
      - log-volume:/var/log
      - storage-volume:/opt/project/storage

  db:
    restart: always
    volumes:
      - log-volume:/var/log

  redis:
    restart: always

