version: '3.7'

services:
  utility:
    env_file:
      - .env
      - .env.local
    image: ubuntu:18.04
    restart: always
    container_name: buzzingpixel-utility
    volumes:
      - .:/opt/project
      - log-volume:/log-volume
      - storage-volume:/storage-volume
    command: bash -c "chmod +x /opt/project/docker/utility/prod.sh && /opt/project/docker/utility/prod.sh"

  app:
    volumes:
      - .:/opt/project:delegated
      - vendor-volume:/opt/project/vendor:delegated
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-dev_default

      # Non-SSL Local
      - traefik.http.routers.buzzingpixel-local.entrypoints=web
      - traefik.http.routers.buzzingpixel-local.rule=Host(`buzzingpixel.localtest.me`)
      - traefik.http.routers.buzzingpixel-local.middlewares=https-redirect

      # Non-SSL Ngrok
      - traefik.http.routers.buzzingpixel-ngrok.entrypoints=web
      - traefik.http.routers.buzzingpixel-ngrok.rule=Host(`buzzingpixel.ngrok.io`)
      - traefik.http.routers.buzzingpixel-ngrok.middlewares=https-redirect

      # SSL Local
      - traefik.http.routers.buzzingpixel-secure-local.entrypoints=websecure
      - traefik.http.routers.buzzingpixel-secure-local.tls=true
      - traefik.http.routers.buzzingpixel-secure-local.rule=Host(`buzzingpixel.localtest.me`)

      # SSL Ngrok
      - traefik.http.routers.buzzingpixel-secure-ngrok.entrypoints=websecure
      - traefik.http.routers.buzzingpixel-secure-ngrok.tls=true
      - traefik.http.routers.buzzingpixel-secure-ngrok.rule=Host(`buzzingpixel.ngrok.io`)

  db:
    volumes:
      - .:/opt/project

  bg-sync-vendor:
    container_name: buzzingpixel-bg-sync-vendor
    image: cweagans/bg-sync
    volumes:
      - vendor-volume:/source
      - ./vendor:/destination:delegated
    privileged: true

volumes:
  vendor-volume:

networks:
  web:
    name: traefik-dev_default
