version: '3.7'

services:
  app:
    env_file:
      - .env
      - .env.local
    container_name: buzzingpixel-app
    image: registry.digitalocean.com/buzzingpixel/buzzingpixel.com-app
    environment:
      HOSTNAME: buzzingpixel-app
    expose:
      - 80
    ports:
      - 14689:80

  db:
    env_file:
      - .env
      - .env.local
    container_name: buzzingpixel-db
    image: postgres:13.2
    environment:
      HOSTNAME: buzzingpixel-db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 14693:5432
    networks:
      default:
        aliases:
          - buzzingpixel-db

volumes:
  db-volume:
