version: '3.7'

services:
  ssh:
    env_file: .env.local
    image: panubo/sshd:1.2.0
    container_name: buzzingpixel-ssh
    tty: true
    volumes:
      - .:/opt/project
      - /Users/tj/.ssh/id_rsa:/tmp/.ssh/id_rsa
      - /Users/tj/.ssh/id_rsa.pub:/tmp/.ssh/id_rsa.pub
