version: '3.7'

services:
  web:
    build:
      target: dev
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/opt/project:delegated
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/nginx.conf:delegated
      - ./docker/web/certs/buzzingpixel.localtest.me.cert:/etc/letsencrypt/live/www.buzzingpixel.com/fullchain.pem:delegated
      - ./docker/web/certs/buzzingpixel.localtest.me.key:/etc/letsencrypt/live/www.buzzingpixel.com/privkey.pem:delegated
    networks:
      default:
        aliases:
          - buzzingpixel.localtest.me
          - buzzingpixel.ngrok.io

  php:
    build:
      target: dev
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/opt/project:delegated
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - .:/opt/project:delegated

volumes:
  storage-volume:
  vendor-volume:
