version: '3.7'

services:
  app:
    env_file:
      - .env
      - .env.local
    container_name: buzzingpixel-app
    image: ghcr.io/buzzingpixel/buzzingpixel.com-app
    environment:
      HOSTNAME: buzzingpixel-app
    expose:
      - 80
    ports:
      - "14689:80"

  db:
    env_file:
      - .env
      - .env.local
    container_name: buzzingpixel-db
    image: postgres:13.2
    environment:
      HOSTNAME: buzzingpixel-db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "14693:5432"
    networks:
      default:
        aliases:
          - buzzingpixel-db

  redis:
    container_name: buzzingpixel-redis
    image: redis:alpine3.14
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - buzzingpixel-redis

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: es01
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      default:
        aliases:
          - buzzingpixel-elasticsearch

volumes:
  db-volume:
  elasticsearch-data-volume:
  log-volume:
  redis-volume:
  storage-volume:
