version: '3.7'

services:
  utility:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - .env
      - .env.local
    image: ghcr.io/buzzingpixel/buzzingpixel.com-utility
    volumes:
      - files-volume:/files-volume
      - storage-volume:/storage-volume

  app:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
      labels:
        ## Traefik config ##
        - traefik.enable=true
        - traefik.http.services.buzzingpixel_prod.loadbalancer.server.port=80
        - traefik.docker.lbswarm=true

        ## Redirect non-www to www
        # WWW Redirect Middleware
        - traefik.http.middlewares.buzzingpixel_www_redirect_regex.redirectregex.regex=^http(s?)://buzzingpixel.com/(.*)
        - traefik.http.middlewares.buzzingpixel_www_redirect_regex.redirectregex.replacement=https://www.buzzingpixel.com/$${2}
        - traefik.http.middlewares.buzzingpixel_www_redirect_regex.redirectregex.permanent=true
        # Insecure redirect
        - traefik.http.routers.buzzingpixel_www_redirect_router.entrypoints=web
        - traefik.http.routers.buzzingpixel_www_redirect_router.rule=Host(`buzzingpixel.com`)
        - traefik.http.routers.buzzingpixel_www_redirect_router.middlewares=buzzingpixel_www_redirect_regex
        # Secure redirect
        - traefik.http.routers.buzzingpixel_secure_www_redirect_router.entrypoints=websecure
        - traefik.http.routers.buzzingpixel_secure_www_redirect_router.rule=Host(`buzzingpixel.com`)
        - traefik.http.routers.buzzingpixel_secure_www_redirect_router.tls=true
        - traefik.http.routers.buzzingpixel_secure_www_redirect_router.middlewares=buzzingpixel_www_redirect_regex
        ## END Redirect non-www to www

        - traefik.http.routers.buzzingpixel_prod.entrypoints=web
        - traefik.http.routers.buzzingpixel_prod.rule=Host(`www.buzzingpixel.com`)
        - traefik.http.routers.buzzingpixel_prod.middlewares=https-redirect
        - traefik.http.routers.buzzingpixel_prod_secure.entrypoints=websecure
        - traefik.http.routers.buzzingpixel_prod_secure.tls=true
        - traefik.http.routers.buzzingpixel_prod_secure.rule=Host(`www.buzzingpixel.com`)
        ## HSTS Settings
        - traefik.http.middlewares.buzzingpixel_hsts.headers.stsincludesubdomains=true
        - traefik.http.middlewares.buzzingpixel_hsts.headers.stspreload=true
        - traefik.http.middlewares.buzzingpixel_hsts.headers.stsseconds=31536000
        ## X-Content-Type-Options
        - traefik.http.middlewares.buzzingpixel_x_content_type.headers.contentTypeNosniff=true
        ## Set the middlewares for HSTS and X-Content-Type-Options
        - traefik.http.routers.buzzingpixel_prod_secure.middlewares=buzzingpixel_hsts,buzzingpixel_x_content_type
    env_file:
      - .env
      - .env.local
    image: ghcr.io/buzzingpixel/buzzingpixel.com-app
    environment:
      HOSTNAME: buzzingpixel-app
      ENABLE_DI_COMPILATION: 1
    volumes:
      - files-volume:/var/www/public/files
      - storage-volume:/var/www/storage
    networks:
      - traefik
      - default

  app-scheduled-task-runner:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - .env
      - .env.local
    image: ghcr.io/buzzingpixel/buzzingpixel.com-app-schedule-runner
    environment:
      HOSTNAME: buzzingpixel-app-scheduled-task-runner
    volumes:
      - files-volume:/var/www/public/files
      - storage-volume:/var/www/storage
    healthcheck:
      disable: true

  app-queue-consumer-1:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - .env
      - .env.local
    image: ghcr.io/buzzingpixel/buzzingpixel.com-app
    environment:
      - HOSTNAME=buzzingpixel-app-queue-consumer-1
    volumes:
      - files-volume:/var/www/public/files
      - storage-volume:/var/www/storage
    healthcheck:
      disable: true
    entrypoint: >-
      /bin/bash -c
      "echo 'while /usr/local/bin/php /var/www/cli queue:run --quiet 2>&1; do sleep 0.2; done' > /runner.sh
      && chmod +x /runner.sh
      && /runner.sh"

  db:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - .env
      - .env.local
    image: ghcr.io/buzzingpixel/buzzingpixel.com-db
    environment:
      HOSTNAME: buzzingpixel-db
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      traefik:
      default:
        aliases:
          - buzzingpixel-db

  redis:
    image: redis:alpine3.14
    volumes:
      - redis-volume:/data
    networks:
      default:
        aliases:
          - buzzingpixel-redis

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
          - buzzingpixel-elasticsearch

networks:
  traefik:
    name: traefik
    external: true

volumes:
  db-volume:
  elasticsearch-data-volume:
  files-volume:
  redis-volume:
  storage-volume:
