version: '3.7'

services:
  traefik:
    container_name: buzzingpixel-traefik
    image: traefik:2.4.8
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
    ports:
      - target: 80
        published: 14690
        mode: host
      - target: 443
        published: 14691
        mode: host
      - target: 8080
        published: 14692
        mode: host
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=traefik_dynamic_conf.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --accesslog
      - --log
    volumes:
      - ./docker/application/certs:/certs
      - ./docker-traefik-dev-conf.yml:/traefik_dynamic_conf.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    volumes:
      - .:/opt/project:delegated
    labels:
      - traefik.enable=true
      # Non-SSL Local
      - traefik.http.routers.app-local.entrypoints=web
      - traefik.http.routers.app-local.rule=Host(`buzzingpixel.localtest.me`)
      - traefik.http.routers.app-local.middlewares=https-redirect

      # Non-SSL Ngrok
      - traefik.http.routers.app-ngrok.entrypoints=web
      - traefik.http.routers.app-ngrok.rule=Host(`buzzingpixel.ngrok.io`)
      - traefik.http.routers.app-ngrok.middlewares=https-redirect

      # SSL Local
      - traefik.http.routers.app-secure-local.entrypoints=websecure
      - traefik.http.routers.app-secure-local.tls=true
      - traefik.http.routers.app-secure-local.rule=Host(`buzzingpixel.localtest.me`)

      # SSL Ngrok
      - traefik.http.routers.app-secure-ngrok.entrypoints=websecure
      - traefik.http.routers.app-secure-ngrok.tls=true
      - traefik.http.routers.app-secure-ngrok.rule=Host(`buzzingpixel.ngrok.io`)

  db:
    volumes:
      - .:/opt/project:delegated
