#!/usr/bin/with-contenv bash
set -e

ENABLE_XDEBUG="${ENABLE_XDEBUG:-0}"

#
# Enable Xdebug right before running the PHP process to avoid unnecessary
# slowness during startup
#

if [ "$ENABLE_XDEBUG" = "1" ]
then
    mv ${PHP_INI_DIR}/disabled/xdebug.ini ${PHP_INI_DIR}/conf.d/
fi

if [ "$ENABLE_DI_COMPILATION" = "1" ]
then
    /usr/local/bin/php /var/www/cli orm:generate-proxies --no-ansi --no-interaction
fi

exec php-fpm -F
