<?php

declare(strict_types=1);

namespace App\Http\Response\Admin\NewLicense\NewLicenseIndex\CreateNewLicense;

use App\Context\Licenses\Entities\License;
use App\Context\Licenses\LicenseApi;
use App\Context\Software\Entities\Software;
use App\Context\Users\Entities\User;
use App\Payload\Payload;

use function assert;

class CreateNewLicense implements CreateNewLicenseContract
{
    public function __construct(private LicenseApi $licenseApi)
    {
    }

    public function create(?User $user, ?Software $software,): Payload
    {
        assert($user instanceof User);
        assert($software instanceof Software);

        $license = new License(
            majorVersion: $software->versions()->first()->majorVersion(),
            licenseKey: $this->licenseApi->generateLicenseKey(),
            adminNotes: 'Generated by admin',
            user: $user,
            software: $software,
        );

        return $this->licenseApi->saveLicense($license);
    }
}
